// Generated by Enunciate
package org.sonatype.nexus.rest.model;

/**
 *  Artifact hit link details sent back on search requests.
 *  
 *  @version $Revision$ $Date$
 */
@javax.xml.bind.annotation.XmlType (
  name = "artifactLink",
  namespace = ""
)
public class NexusNGArtifactLink implements java.io.Serializable {

  private java.lang.String _classifier;
  private java.lang.String _extension;

  /**
   * The classifier of the artifact.
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "classifier",
    namespace = ""
  )
  public java.lang.String getClassifier() {
    return this._classifier;
  }

  /**
   * The classifier of the artifact.
   */
  public void setClassifier(java.lang.String _classifier) {
    this._classifier = _classifier;
  }

  /**
   * The extension of the artifact.
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "extension",
    namespace = ""
  )
  public java.lang.String getExtension() {
    return this._extension;
  }

  /**
   * The extension of the artifact.
   */
  public void setExtension(java.lang.String _extension) {
    this._extension = _extension;
  }

}
