// Generated by Enunciate
package org.sonatype.nexus.rest.model;

/**
 *  Class NexusIndexerResponse.
 *  
 *  @version $Revision$ $Date$
 */
@javax.xml.bind.annotation.XmlType (
  name = "nexusIndexerResponse",
  namespace = ""
)
public class NexusIndexerResponse extends org.sonatype.nexus.rest.model.NexusResponse {


}
