// Generated by Enunciate
package org.sonatype.nexus.rest.model;

/**
 *  The repository url information for a given artifact.
 *  
 *  @version $Revision$ $Date$
 */
@javax.xml.bind.annotation.XmlType (
  name = "repository-url-resource",
  namespace = ""
)
public class RepositoryUrlResource implements java.io.Serializable {

  private java.lang.String _repositoryId;
  private java.lang.String _repositoryName;
  private java.lang.String _path;
  private java.lang.String _artifactUrl;
  private boolean _canView;

  /**
   * The repository where the artifact is stored.
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "repositoryId",
    namespace = ""
  )
  public java.lang.String getRepositoryId() {
    return this._repositoryId;
  }

  /**
   * The repository where the artifact is stored.
   */
  public void setRepositoryId(java.lang.String _repositoryId) {
    this._repositoryId = _repositoryId;
  }

  /**
   * The repository where the artifact is stored.
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "repositoryName",
    namespace = ""
  )
  public java.lang.String getRepositoryName() {
    return this._repositoryName;
  }

  /**
   * The repository where the artifact is stored.
   */
  public void setRepositoryName(java.lang.String _repositoryName) {
    this._repositoryName = _repositoryName;
  }

  /**
   * The artifact path.
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "path",
    namespace = ""
  )
  public java.lang.String getPath() {
    return this._path;
  }

  /**
   * The artifact path.
   */
  public void setPath(java.lang.String _path) {
    this._path = _path;
  }

  /**
   * The artifact url.
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "artifactUrl",
    namespace = ""
  )
  public java.lang.String getArtifactUrl() {
    return this._artifactUrl;
  }

  /**
   * The artifact url.
   */
  public void setArtifactUrl(java.lang.String _artifactUrl) {
    this._artifactUrl = _artifactUrl;
  }

  /**
   * Tells if the users has view access to a given artifact.
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "canView",
    namespace = ""
  )
  public boolean getCanView() {
    return this._canView;
  }

  /**
   * Tells if the users has view access to a given artifact.
   */
  public void setCanView(boolean _canView) {
    this._canView = _canView;
  }

}
