/*
 * Copyright (C) 2012 Pieter van der Meer (pieter(at)elucidator.nl)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by Enunciate
package org.sonatype.nexus.rest.model;

/**
 *  REST Response object for a artifact-info resource request,
 *  contains the typical 'data' parameter,
 *          which is the content items requested.
 *  
 *  @version $Revision$ $Date$
 */
@javax.xml.bind.annotation.XmlType (
  name = "artifactInfoResourceResponse",
  namespace = ""
)
@javax.xml.bind.annotation.XmlRootElement (
  name = "artifact-info",
  namespace = ""
)
public class ArtifactInfoResourceResponse extends org.sonatype.nexus.rest.model.NexusIndexerResponse {

  private org.sonatype.nexus.rest.model.ArtifactInfoResource _data;

  /**
   * List of describe items, that will contain useful information
   * about the retrieved data.
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "data",
    namespace = ""
  )
  public org.sonatype.nexus.rest.model.ArtifactInfoResource getData() {
    return this._data;
  }

  /**
   * List of describe items, that will contain useful information
   * about the retrieved data.
   */
  public void setData(org.sonatype.nexus.rest.model.ArtifactInfoResource _data) {
    this._data = _data;
  }

}
