// Generated by Enunciate
package org.sonatype.nexus.rest.model;

/**
 *  REST Response object for a artifact-info resource request,
 *  contains the typical 'data' parameter,
 *          which is the content items requested.
 *  
 *  @version $Revision$ $Date$
 */
@javax.xml.bind.annotation.XmlType (
  name = "artifactInfoResourceResponse",
  namespace = ""
)
@javax.xml.bind.annotation.XmlRootElement (
  name = "artifact-info",
  namespace = ""
)
public class ArtifactInfoResourceResponse extends org.sonatype.nexus.rest.model.NexusIndexerResponse {

  private org.sonatype.nexus.rest.model.ArtifactInfoResource _data;

  /**
   * List of describe items, that will contain useful information
   * about the retrieved data.
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "data",
    namespace = ""
  )
  public org.sonatype.nexus.rest.model.ArtifactInfoResource getData() {
    return this._data;
  }

  /**
   * List of describe items, that will contain useful information
   * about the retrieved data.
   */
  public void setData(org.sonatype.nexus.rest.model.ArtifactInfoResource _data) {
    this._data = _data;
  }

}
