// Generated by Enunciate
package org.sonatype.nexus.rest.model;

/**
 *  Artifact repository details sent back on search requests.
 *  
 *  @version $Revision$ $Date$
 */
@javax.xml.bind.annotation.XmlType (
  name = "repositoryDetail",
  namespace = ""
)
public class NexusNGRepositoryDetail implements java.io.Serializable {

  private java.lang.String _repositoryId;
  private java.lang.String _repositoryName;
  private java.lang.String _repositoryContentClass;
  private java.lang.String _repositoryKind;
  private java.lang.String _repositoryPolicy;
  private java.lang.String _repositoryURL;

  /**
   * The repository ID.
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "repositoryId",
    namespace = ""
  )
  public java.lang.String getRepositoryId() {
    return this._repositoryId;
  }

  /**
   * The repository ID.
   */
  public void setRepositoryId(java.lang.String _repositoryId) {
    this._repositoryId = _repositoryId;
  }

  /**
   * The repository name.
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "repositoryName",
    namespace = ""
  )
  public java.lang.String getRepositoryName() {
    return this._repositoryName;
  }

  /**
   * The repository name.
   */
  public void setRepositoryName(java.lang.String _repositoryName) {
    this._repositoryName = _repositoryName;
  }

  /**
   * The repository content class.
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "repositoryContentClass",
    namespace = ""
  )
  public java.lang.String getRepositoryContentClass() {
    return this._repositoryContentClass;
  }

  /**
   * The repository content class.
   */
  public void setRepositoryContentClass(java.lang.String _repositoryContentClass) {
    this._repositoryContentClass = _repositoryContentClass;
  }

  /**
   * The repository kind (hosted, proxy, group).
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "repositoryKind",
    namespace = ""
  )
  public java.lang.String getRepositoryKind() {
    return this._repositoryKind;
  }

  /**
   * The repository kind (hosted, proxy, group).
   */
  public void setRepositoryKind(java.lang.String _repositoryKind) {
    this._repositoryKind = _repositoryKind;
  }

  /**
   * The repository policy (RELEASE or SNAPSHOT).
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "repositoryPolicy",
    namespace = ""
  )
  public java.lang.String getRepositoryPolicy() {
    return this._repositoryPolicy;
  }

  /**
   * The repository policy (RELEASE or SNAPSHOT).
   */
  public void setRepositoryPolicy(java.lang.String _repositoryPolicy) {
    this._repositoryPolicy = _repositoryPolicy;
  }

  /**
   * The repository base URL.
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "repositoryURL",
    namespace = ""
  )
  public java.lang.String getRepositoryURL() {
    return this._repositoryURL;
  }

  /**
   * The repository base URL.
   */
  public void setRepositoryURL(java.lang.String _repositoryURL) {
    this._repositoryURL = _repositoryURL;
  }

}
