// Generated by Enunciate
package org.sonatype.nexus.rest.model;

/**
 * (no documentation provided)
 */
@javax.xml.bind.annotation.XmlType (
  name = "nexusResponse",
  namespace = ""
)
public class NexusResponse implements java.io.Serializable {


}
