/*
 * Copyright (C) 2012 Pieter van der Meer (pieter(at)elucidator.nl)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by Enunciate
package org.sonatype.nexus.rest.model;

/**
 *  Artifact hit link details sent back on search requests.
 *  
 *  @version $Revision$ $Date$
 */
@javax.xml.bind.annotation.XmlType (
  name = "artifactLink",
  namespace = ""
)
public class NexusNGArtifactLink implements java.io.Serializable {

  private java.lang.String _classifier;
  private java.lang.String _extension;

  /**
   * The classifier of the artifact.
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "classifier",
    namespace = ""
  )
  public java.lang.String getClassifier() {
    return this._classifier;
  }

  /**
   * The classifier of the artifact.
   */
  public void setClassifier(java.lang.String _classifier) {
    this._classifier = _classifier;
  }

  /**
   * The extension of the artifact.
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "extension",
    namespace = ""
  )
  public java.lang.String getExtension() {
    return this._extension;
  }

  /**
   * The extension of the artifact.
   */
  public void setExtension(java.lang.String _extension) {
    this._extension = _extension;
  }

}
