// Generated by Enunciate
package org.sonatype.nexus.rest.model;

/**
 *  Artifact details sent back on search requests.
 *  
 *  @version $Revision$ $Date$
 */
@javax.xml.bind.annotation.XmlType (
  name = "nexusNGArtifact",
  namespace = ""
)
public class NexusNGArtifact implements java.io.Serializable {

  private java.lang.String _groupId;
  private java.lang.String _artifactId;
  private java.lang.String _version;
  private java.lang.String _latestSnapshot;
  private java.lang.String _latestSnapshotRepositoryId;
  private java.lang.String _latestRelease;
  private java.lang.String _latestReleaseRepositoryId;
  private java.lang.String _highlightedFragment;
  private java.util.List<org.sonatype.nexus.rest.model.NexusNGArtifactHit> _artifactHits;

  /**
   * The group id of the artifact.
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "groupId",
    namespace = ""
  )
  public java.lang.String getGroupId() {
    return this._groupId;
  }

  /**
   * The group id of the artifact.
   */
  public void setGroupId(java.lang.String _groupId) {
    this._groupId = _groupId;
  }

  /**
   * The artifact id of the artifact.
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "artifactId",
    namespace = ""
  )
  public java.lang.String getArtifactId() {
    return this._artifactId;
  }

  /**
   * The artifact id of the artifact.
   */
  public void setArtifactId(java.lang.String _artifactId) {
    this._artifactId = _artifactId;
  }

  /**
   * The version of the artifact.
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "version",
    namespace = ""
  )
  public java.lang.String getVersion() {
    return this._version;
  }

  /**
   * The version of the artifact.
   */
  public void setVersion(java.lang.String _version) {
    this._version = _version;
  }

  /**
   * The latest snapshot version of the artifact.
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "latestSnapshot",
    namespace = ""
  )
  public java.lang.String getLatestSnapshot() {
    return this._latestSnapshot;
  }

  /**
   * The latest snapshot version of the artifact.
   */
  public void setLatestSnapshot(java.lang.String _latestSnapshot) {
    this._latestSnapshot = _latestSnapshot;
  }

  /**
   * The repository of latest snapshot version of the artifact.
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "latestSnapshotRepositoryId",
    namespace = ""
  )
  public java.lang.String getLatestSnapshotRepositoryId() {
    return this._latestSnapshotRepositoryId;
  }

  /**
   * The repository of latest snapshot version of the artifact.
   */
  public void setLatestSnapshotRepositoryId(java.lang.String _latestSnapshotRepositoryId) {
    this._latestSnapshotRepositoryId = _latestSnapshotRepositoryId;
  }

  /**
   * The latest release version of the artifact.
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "latestRelease",
    namespace = ""
  )
  public java.lang.String getLatestRelease() {
    return this._latestRelease;
  }

  /**
   * The latest release version of the artifact.
   */
  public void setLatestRelease(java.lang.String _latestRelease) {
    this._latestRelease = _latestRelease;
  }

  /**
   * The repository of latest release version of the artifact.
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "latestReleaseRepositoryId",
    namespace = ""
  )
  public java.lang.String getLatestReleaseRepositoryId() {
    return this._latestReleaseRepositoryId;
  }

  /**
   * The repository of latest release version of the artifact.
   */
  public void setLatestReleaseRepositoryId(java.lang.String _latestReleaseRepositoryId) {
    this._latestReleaseRepositoryId = _latestReleaseRepositoryId;
  }

  /**
   * A HTML highlighted fragment of the matched hit.
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "highlightedFragment",
    namespace = ""
  )
  public java.lang.String getHighlightedFragment() {
    return this._highlightedFragment;
  }

  /**
   * A HTML highlighted fragment of the matched hit.
   */
  public void setHighlightedFragment(java.lang.String _highlightedFragment) {
    this._highlightedFragment = _highlightedFragment;
  }

  /**
   * Field artifactHits.
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "artifactHit",
    namespace = ""
  )
  @javax.xml.bind.annotation.XmlElementWrapper (
    name = "artifactHits",
    namespace = ""
  )
  public java.util.List<org.sonatype.nexus.rest.model.NexusNGArtifactHit> getArtifactHits() {
    return this._artifactHits;
  }

  /**
   * Field artifactHits.
   */
  public void setArtifactHits(java.util.List<org.sonatype.nexus.rest.model.NexusNGArtifactHit> _artifactHits) {
    this._artifactHits = _artifactHits;
  }

}
