/*
 * Copyright (C) 2012 Pieter van der Meer (pieter(at)elucidator.nl)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by Enunciate
package org.sonatype.nexus.rest.model;

/**
 *  Artifact details sent back on search requests.
 *  
 *  @version $Revision$ $Date$
 */
@javax.xml.bind.annotation.XmlType (
  name = "nexus-artifact",
  namespace = ""
)
public class NexusArtifact implements java.io.Serializable {

  private java.lang.String _resourceURI;
  private java.lang.String _groupId;
  private java.lang.String _artifactId;
  private java.lang.String _version;
  private java.lang.String _classifier;
  private java.lang.String _packaging;
  private java.lang.String _extension;
  private java.lang.String _repoId;
  private java.lang.String _contextId;
  private java.lang.String _pomLink;
  private java.lang.String _artifactLink;
  private java.lang.String _highlightedFragment;

  /**
   * The URL that can be used to retrieve the artifact.
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "resourceURI",
    namespace = ""
  )
  public java.lang.String getResourceURI() {
    return this._resourceURI;
  }

  /**
   * The URL that can be used to retrieve the artifact.
   */
  public void setResourceURI(java.lang.String _resourceURI) {
    this._resourceURI = _resourceURI;
  }

  /**
   * The group id of the artifact.
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "groupId",
    namespace = ""
  )
  public java.lang.String getGroupId() {
    return this._groupId;
  }

  /**
   * The group id of the artifact.
   */
  public void setGroupId(java.lang.String _groupId) {
    this._groupId = _groupId;
  }

  /**
   * The artifact id of the artifact.
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "artifactId",
    namespace = ""
  )
  public java.lang.String getArtifactId() {
    return this._artifactId;
  }

  /**
   * The artifact id of the artifact.
   */
  public void setArtifactId(java.lang.String _artifactId) {
    this._artifactId = _artifactId;
  }

  /**
   * The version of the artifact.
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "version",
    namespace = ""
  )
  public java.lang.String getVersion() {
    return this._version;
  }

  /**
   * The version of the artifact.
   */
  public void setVersion(java.lang.String _version) {
    this._version = _version;
  }

  /**
   * The classifier of the artifact.
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "classifier",
    namespace = ""
  )
  public java.lang.String getClassifier() {
    return this._classifier;
  }

  /**
   * The classifier of the artifact.
   */
  public void setClassifier(java.lang.String _classifier) {
    this._classifier = _classifier;
  }

  /**
   * The packaging of the artifact.
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "packaging",
    namespace = ""
  )
  public java.lang.String getPackaging() {
    return this._packaging;
  }

  /**
   * The packaging of the artifact.
   */
  public void setPackaging(java.lang.String _packaging) {
    this._packaging = _packaging;
  }

  /**
   * The extension of the artifact.
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "extension",
    namespace = ""
  )
  public java.lang.String getExtension() {
    return this._extension;
  }

  /**
   * The extension of the artifact.
   */
  public void setExtension(java.lang.String _extension) {
    this._extension = _extension;
  }

  /**
   * The repository id where the artifact is stored.
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "repoId",
    namespace = ""
  )
  public java.lang.String getRepoId() {
    return this._repoId;
  }

  /**
   * The repository id where the artifact is stored.
   */
  public void setRepoId(java.lang.String _repoId) {
    this._repoId = _repoId;
  }

  /**
   * The indexing context where the artifact is indexed.
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "contextId",
    namespace = ""
  )
  public java.lang.String getContextId() {
    return this._contextId;
  }

  /**
   * The indexing context where the artifact is indexed.
   */
  public void setContextId(java.lang.String _contextId) {
    this._contextId = _contextId;
  }

  /**
   * URL that would give you the pom file.
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "pomLink",
    namespace = ""
  )
  public java.lang.String getPomLink() {
    return this._pomLink;
  }

  /**
   * URL that would give you the pom file.
   */
  public void setPomLink(java.lang.String _pomLink) {
    this._pomLink = _pomLink;
  }

  /**
   * URL that would give you the artifact file.
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "artifactLink",
    namespace = ""
  )
  public java.lang.String getArtifactLink() {
    return this._artifactLink;
  }

  /**
   * URL that would give you the artifact file.
   */
  public void setArtifactLink(java.lang.String _artifactLink) {
    this._artifactLink = _artifactLink;
  }

  /**
   * A HTML highlighted fragment of the matched hit.
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "highlightedFragment",
    namespace = ""
  )
  public java.lang.String getHighlightedFragment() {
    return this._highlightedFragment;
  }

  /**
   * A HTML highlighted fragment of the matched hit.
   */
  public void setHighlightedFragment(java.lang.String _highlightedFragment) {
    this._highlightedFragment = _highlightedFragment;
  }

}
