/*
 * Copyright (C) 2012 Pieter van der Meer (pieter(at)elucidator.nl)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by Enunciate
package org.sonatype.nexus.rest.model;

/**
 *  Artifact hit details sent back on search requests.
 *  
 *  @version $Revision$ $Date$
 */
@javax.xml.bind.annotation.XmlType (
  name = "artifactHit",
  namespace = ""
)
public class NexusNGArtifactHit implements java.io.Serializable {

  private java.lang.String _repositoryId;
  private java.util.List<org.sonatype.nexus.rest.model.NexusNGArtifactLink> _artifactLinks;

  /**
   * The repository ID.
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "repositoryId",
    namespace = ""
  )
  public java.lang.String getRepositoryId() {
    return this._repositoryId;
  }

  /**
   * The repository ID.
   */
  public void setRepositoryId(java.lang.String _repositoryId) {
    this._repositoryId = _repositoryId;
  }

  /**
   * Field artifactLinks.
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "artifactLink",
    namespace = ""
  )
  @javax.xml.bind.annotation.XmlElementWrapper (
    name = "artifactLinks",
    namespace = ""
  )
  public java.util.List<org.sonatype.nexus.rest.model.NexusNGArtifactLink> getArtifactLinks() {
    return this._artifactLinks;
  }

  /**
   * Field artifactLinks.
   */
  public void setArtifactLinks(java.util.List<org.sonatype.nexus.rest.model.NexusNGArtifactLink> _artifactLinks) {
    this._artifactLinks = _artifactLinks;
  }

}
