// Generated by Enunciate
package org.sonatype.nexus.rest.model;

/**
 *  Artifact hit details sent back on search requests.
 *  
 *  @version $Revision$ $Date$
 */
@javax.xml.bind.annotation.XmlType (
  name = "artifactHit",
  namespace = ""
)
public class NexusNGArtifactHit implements java.io.Serializable {

  private java.lang.String _repositoryId;
  private java.util.List<org.sonatype.nexus.rest.model.NexusNGArtifactLink> _artifactLinks;

  /**
   * The repository ID.
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "repositoryId",
    namespace = ""
  )
  public java.lang.String getRepositoryId() {
    return this._repositoryId;
  }

  /**
   * The repository ID.
   */
  public void setRepositoryId(java.lang.String _repositoryId) {
    this._repositoryId = _repositoryId;
  }

  /**
   * Field artifactLinks.
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "artifactLink",
    namespace = ""
  )
  @javax.xml.bind.annotation.XmlElementWrapper (
    name = "artifactLinks",
    namespace = ""
  )
  public java.util.List<org.sonatype.nexus.rest.model.NexusNGArtifactLink> getArtifactLinks() {
    return this._artifactLinks;
  }

  /**
   * Field artifactLinks.
   */
  public void setArtifactLinks(java.util.List<org.sonatype.nexus.rest.model.NexusNGArtifactLink> _artifactLinks) {
    this._artifactLinks = _artifactLinks;
  }

}
