/*
 * Copyright (C) 2012 Pieter van der Meer (pieter(at)elucidator.nl)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by Enunciate
package org.sonatype.nexus.rest.model;

/**
 *  REST Response object for a list of search results, contains the
 *  typical 'data' parameter, which is a
 *          list of search results.
 *  
 *  @version $Revision$ $Date$
 */
@javax.xml.bind.annotation.XmlType (
  name = "searchResponse",
  namespace = ""
)
@javax.xml.bind.annotation.XmlRootElement (
  name = "search-results",
  namespace = ""
)
public class SearchResponse extends org.sonatype.nexus.rest.model.NexusIndexerResponse {

  private int _totalCount;
  private int _from;
  private int _count;
  private boolean _tooManyResults;
  private java.util.List<org.sonatype.nexus.rest.model.NexusArtifact> _data;

  /**
   * The total number of results.
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "totalCount",
    namespace = ""
  )
  public int getTotalCount() {
    return this._totalCount;
  }

  /**
   * The total number of results.
   */
  public void setTotalCount(int _totalCount) {
    this._totalCount = _totalCount;
  }

  /**
   * The starting index of the results.
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "from",
    namespace = ""
  )
  public int getFrom() {
    return this._from;
  }

  /**
   * The starting index of the results.
   */
  public void setFrom(int _from) {
    this._from = _from;
  }

  /**
   * The number of results in this response.
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "count",
    namespace = ""
  )
  public int getCount() {
    return this._count;
  }

  /**
   * The number of results in this response.
   */
  public void setCount(int _count) {
    this._count = _count;
  }

  /**
   * Flag that states if too many results were found.
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "tooManyResults",
    namespace = ""
  )
  public boolean getTooManyResults() {
    return this._tooManyResults;
  }

  /**
   * Flag that states if too many results were found.
   */
  public void setTooManyResults(boolean _tooManyResults) {
    this._tooManyResults = _tooManyResults;
  }

  /**
   * Field data.
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "artifact",
    namespace = ""
  )
  @javax.xml.bind.annotation.XmlElementWrapper (
    name = "data",
    namespace = ""
  )
  public java.util.List<org.sonatype.nexus.rest.model.NexusArtifact> getData() {
    return this._data;
  }

  /**
   * Field data.
   */
  public void setData(java.util.List<org.sonatype.nexus.rest.model.NexusArtifact> _data) {
    this._data = _data;
  }

}
